import {
  ActivityIcon,
  AlignCenterIcon,
  AlignJustifyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  ArrowLeftRightIcon,
  AsteriskIcon,
  BoldIcon,
  BoxIcon,
  BracesIcon,
  BracketsIcon,
  Calendar1Icon,
  CalendarIcon,
  ChartPieIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsLeftIcon,
  ChevronsRightIcon,
  ChevronsUpDownIcon,
  ChevronUpIcon,
  CircleCheck,
  CircleIcon,
  CircleUserRoundIcon,
  ClockIcon,
  CombineIcon,
  CopyIcon,
  DatabaseIcon,
  EditIcon,
  EyeIcon,
  EyeOffIcon,
  FileIcon,
  FilterIcon,
  FolderTreeIcon,
  GitPullRequestCreateIcon,
  GitPullRequestIcon,
  GlobeIcon,
  GripHorizontalIcon,
  GripVerticalIcon,
  HashIcon,
  Heading1Icon,
  Heading2Icon,
  Heading3Icon,
  Heading4Icon,
  Heading5Icon,
  Heading6Icon,
  HeadingIcon,
  ImageIcon,
  ItalicIcon,
  LayersIcon,
  LayoutIcon,
  ListIcon,
  ListOrderedIcon,
  LoaderCircleIcon,
  LockIcon,
  LogInIcon,
  LogOutIcon,
  LucideIcon,
  MailIcon,
  MenuIcon,
  MoonIcon,
  MoreHorizontalIcon,
  MoveDownIcon,
  MoveUpIcon,
  PlusIcon,
  RabbitIcon,
  RectangleEllipsisIcon,
  RedoIcon,
  RefreshCwIcon,
  SaveIcon,
  SearchIcon,
  ServerIcon,
  Settings2Icon,
  SettingsIcon,
  ShieldIcon,
  SquareCheckIcon,
  SquareMousePointerIcon,
  StarIcon,
  StarOffIcon,
  StrikethroughIcon,
  SubscriptIcon,
  SunIcon,
  SunMoonIcon,
  SuperscriptIcon,
  TableIcon,
  TextCursorInput,
  ToggleRight,
  TrashIcon,
  TypeIcon,
  UnderlineIcon,
  UndoIcon,
  UserIcon,
  UserPenIcon,
  UsersIcon,
  XIcon,
} from "lucide-react";

type RegistryItem = LucideIcon | React.ComponentType<React.SVGProps<SVGSVGElement>>;

type Registry = Record<string, RegistryItem>;

const defaultRegistry: Registry = {
  ["align-center"]: AlignCenterIcon,
  ["align-justify"]: AlignJustifyIcon,
  ["align-left"]: AlignLeftIcon,
  ["align-right"]: AlignRightIcon,
  ["array"]: BracketsIcon,
  ["asterisk"]: AsteriskIcon,
  ["bold"]: BoldIcon,
  ["box"]: BoxIcon,
  ["braces"]: BracesIcon,
  ["builder"]: CombineIcon,
  ["calendar"]: CalendarIcon,
  ["chart-pie"]: ChartPieIcon,
  ["check"]: CheckIcon,
  ["checkbox"]: SquareCheckIcon,
  ["chevron-down"]: ChevronDownIcon,
  ["chevron-left"]: ChevronLeftIcon,
  ["chevron-right"]: ChevronRightIcon,
  ["chevron-up"]: ChevronUpIcon,
  ["chevrons-left"]: ChevronsLeftIcon,
  ["chevrons-right"]: ChevronsRightIcon,
  ["chevrons-up-down"]: ChevronsUpDownIcon,
  ["circle-check"]: CircleCheck,
  ["circle-user"]: CircleUserRoundIcon,
  ["circle"]: CircleIcon,
  ["clock"]: ClockIcon,
  ["copy"]: CopyIcon,
  ["database"]: DatabaseIcon,
  ["date"]: Calendar1Icon,
  ["default"]: RabbitIcon,
  ["edit"]: EditIcon,
  ["email"]: MailIcon,
  ["eye-off"]: EyeOffIcon,
  ["eye"]: EyeIcon,
  ["file"]: FileIcon,
  ["filter"]: FilterIcon,
  ["globe"]: GlobeIcon,
  ["grip-horizontal"]: GripHorizontalIcon,
  ["grip-vertical"]: GripVerticalIcon,
  ["heading-1"]: Heading1Icon,
  ["heading-2"]: Heading2Icon,
  ["heading-3"]: Heading3Icon,
  ["heading-4"]: Heading4Icon,
  ["heading-5"]: Heading5Icon,
  ["heading-6"]: Heading6Icon,
  ["heading"]: HeadingIcon,
  ["horizon"]: ActivityIcon,
  ["image"]: ImageIcon,
  ["input"]: RectangleEllipsisIcon,
  ["italic"]: ItalicIcon,
  ["layers"]: LayersIcon,
  ["layout"]: LayoutIcon,
  ["list-bullet"]: ListIcon,
  ["list-ordered"]: ListOrderedIcon,
  ["loader-circle"]: LoaderCircleIcon,
  ["lock"]: LockIcon,
  ["log-in"]: LogInIcon,
  ["log-out"]: LogOutIcon,
  ["menu"]: MenuIcon,
  ["moon"]: MoonIcon,
  ["more-horizontal"]: MoreHorizontalIcon,
  ["move-down"]: MoveDownIcon,
  ["move-up"]: MoveUpIcon,
  ["number"]: HashIcon,
  ["password"]: LockIcon,
  ["plus"]: PlusIcon,
  ["range"]: Settings2Icon,
  ["redo"]: RedoIcon,
  ["refresh"]: RefreshCwIcon,
  ["relations"]: ArrowLeftRightIcon,
  ["rich-text"]: TypeIcon,
  ["save-and-add"]: GitPullRequestCreateIcon,
  ["save-and-continue"]: GitPullRequestIcon,
  ["save"]: SaveIcon,
  ["search"]: SearchIcon,
  ["select"]: SquareMousePointerIcon,
  ["server"]: ServerIcon,
  ["settings"]: SettingsIcon,
  ["shield"]: ShieldIcon,
  ["star-off"]: StarOffIcon,
  ["star"]: StarIcon,
  ["strikethrough"]: StrikethroughIcon,
  ["subscript"]: SubscriptIcon,
  ["sun-moon"]: SunMoonIcon,
  ["sun"]: SunIcon,
  ["superscript"]: SuperscriptIcon,
  ["switch"]: ToggleRight,
  ["table"]: TableIcon,
  ["text"]: TextCursorInput,
  ["time"]: ClockIcon,
  ["trash"]: TrashIcon,
  ["tree"]: FolderTreeIcon,
  ["underline"]: UnderlineIcon,
  ["undo"]: UndoIcon,
  ["user-edit"]: UserPenIcon,
  ["user"]: UserIcon,
  ["users"]: UsersIcon,
  ["x"]: XIcon,
};

type IconName = keyof typeof defaultRegistry;

const registry: Registry = {
  ...defaultRegistry,
};

function getIcon(name: IconName): RegistryItem {
  return registry[name] ?? registry["default"];
}

function setIcon(name: string, component: RegistryItem) {
  registry[name] = component;
}

export { getIcon, setIcon };

export type { IconName };
