import {
  AlignCenterIcon,
  AlignJustifyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  ArrowLeftRightIcon,
  AsteriskIcon,
  BetweenHorizonalStartIcon,
  BoldIcon,
  BoxIcon,
  Calendar1Icon,
  CalendarIcon,
  ChartPieIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsLeftIcon,
  ChevronsRightIcon,
  ChevronsUpDownIcon,
  ChevronUpIcon,
  CircleIcon,
  ClockIcon,
  CombineIcon,
  CopyIcon,
  EditIcon,
  GlobeIcon,
  GripHorizontalIcon,
  GripVerticalIcon,
  HashIcon,
  Heading1Icon,
  Heading2Icon,
  Heading3Icon,
  Heading4Icon,
  Heading5Icon,
  Heading6Icon,
  HeadingIcon,
  ItalicIcon,
  LayoutIcon,
  ListIcon,
  ListOrderedIcon,
  LoaderCircleIcon,
  LockIcon,
  LogInIcon,
  LogOutIcon,
  MailIcon,
  MenuIcon,
  MoreHorizontalIcon,
  PlusIcon,
  RabbitIcon,
  RectangleEllipsisIcon,
  RedoIcon,
  SearchIcon,
  Settings2Icon,
  SettingsIcon,
  ShieldIcon,
  SquareCheckIcon,
  SquareMousePointerIcon,
  StrikethroughIcon,
  SubscriptIcon,
  SuperscriptIcon,
  TableIcon,
  TextCursorInput,
  ToggleRight,
  TrashIcon,
  TypeIcon,
  UnderlineIcon,
  UndoIcon,
  UserPenIcon,
  UsersIcon,
  XIcon,
} from "lucide-react";
import type { ComponentType } from "react";

export type IconName = keyof typeof defaultRegistry;

const defaultRegistry = {
  ["align-center"]: AlignCenterIcon,
  ["align-justify"]: AlignJustifyIcon,
  ["align-left"]: AlignLeftIcon,
  ["align-right"]: AlignRightIcon,
  ["asterisk"]: AsteriskIcon,
  ["bold"]: BoldIcon,
  ["box"]: BoxIcon,
  ["builder"]: CombineIcon,
  ["calendar"]: CalendarIcon,
  ["chart-pie"]: ChartPieIcon,
  ["check"]: CheckIcon,
  ["checkbox"]: SquareCheckIcon,
  ["chevron-down"]: ChevronDownIcon,
  ["chevron-left"]: ChevronLeftIcon,
  ["chevron-right"]: ChevronRightIcon,
  ["chevron-up"]: ChevronUpIcon,
  ["chevrons-left"]: ChevronsLeftIcon,
  ["chevrons-right"]: ChevronsRightIcon,
  ["chevrons-up-down"]: ChevronsUpDownIcon,
  ["circle"]: CircleIcon,
  ["copy"]: CopyIcon,
  ["date"]: Calendar1Icon,
  ["edit"]: EditIcon,
  ["email"]: MailIcon,
  ["globe"]: GlobeIcon,
  ["grip-horizontal"]: GripHorizontalIcon,
  ["grip-vertical"]: GripVerticalIcon,
  ["heading"]: HeadingIcon,
  ["heading-1"]: Heading1Icon,
  ["heading-2"]: Heading2Icon,
  ["heading-3"]: Heading3Icon,
  ["heading-4"]: Heading4Icon,
  ["heading-5"]: Heading5Icon,
  ["heading-6"]: Heading6Icon,
  ["input"]: RectangleEllipsisIcon,
  ["italic"]: ItalicIcon,
  ["layout"]: LayoutIcon,
  ["list-bullet"]: ListIcon,
  ["list-ordered"]: ListOrderedIcon,
  ["loader-circle"]: LoaderCircleIcon,
  ["log-in"]: LogInIcon,
  ["log-out"]: LogOutIcon,
  ["menu"]: MenuIcon,
  ["more-horizontal"]: MoreHorizontalIcon,
  ["number"]: HashIcon,
  ["password"]: LockIcon,
  ["plus"]: PlusIcon,
  ["range"]: Settings2Icon,
  ["redo"]: RedoIcon,
  ["relations"]: ArrowLeftRightIcon,
  ["rich-text"]: TypeIcon,
  ["search"]: SearchIcon,
  ["section"]: BetweenHorizonalStartIcon,
  ["select"]: SquareMousePointerIcon,
  ["settings"]: SettingsIcon,
  ["shield"]: ShieldIcon,
  ["strikethrough"]: StrikethroughIcon,
  ["subscript"]: SubscriptIcon,
  ["superscript"]: SuperscriptIcon,
  ["switch"]: ToggleRight,
  ["table"]: TableIcon,
  ["text"]: TextCursorInput,
  ["time"]: ClockIcon,
  ["trash"]: TrashIcon,
  ["underline"]: UnderlineIcon,
  ["undo"]: UndoIcon,
  ["user-edit"]: UserPenIcon,
  ["users"]: UsersIcon,
  ["x"]: XIcon,
} satisfies Record<string, ComponentType<any>>;

const registry: Record<string, ComponentType<any>> = {
  ...defaultRegistry,
};

export function getIcon(name: IconName): ComponentType<any> {
  return registry[name] ?? RabbitIcon;
}

export function setIcon(name: string, component: ComponentType<any>) {
  registry[name] = component;
}
